name: Lint with Black

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-black:
    name: Lint with Black
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv and Set up Cache
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python using uv
        run: uv python install

      - name: Install Black into system Python
        run: uv pip install black --system

      - name: Run Black Formatter Check
        run: uv run black --check .
