name: MyPy Type Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  mypy-check:
    name: MyPy Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv and Set up Cache
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python using uv
        run: uv python install

      - name: Install dependencies from uv.lock
        run: |
          uv sync --locked --all-extras --dev

      - name: Run MyPy
        run: uv run mypy src
